trigger:
  branches:
    include:
      - dev/*
      - bugfix/*
pr:
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

container: liambindle/penelope:0.1.0-ubuntu16.04-gcc7-netcdf4.5.0-netcdff4.4.4

steps:
- script: |
    module load gcc/7 
    spack load hdf5 
    spack load netcdf 
    spack load netcdf-fortran
    mkdir build
    cd build
    cmake -DRUNDIR=IGNORE -DRUNDIR_SIM=standard $(Build.Repository.LocalPath)
    make -j
    make install
  displayName: 'Building GEOS-Chem'