trigger:
  branches:
    exclude:
      - '*'
  tags:
    include:
      - '*'
    exclude:
      - '*-alpha*'
      - '*-beta*'
      - '*-rc*'
pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Docker@2
    displayName: Login to Docker Hub
    inputs:
      command: login
      containerRegistry: DockerHub
  - task: Docker@2
    displayName: Build image
    inputs:
      command: build
      Dockerfile: ci-release.dockerfile
      repository: liambindle/geos-chem
      tags: |
        latest
      arguments: |
        --build-arg GC_SRC=$(Build.Repository.LocalPath)
  - task: Docker@2
    displayName: Push image
    inputs:
      containerRegistry: DockerHub
      repository: liambindle/geos-chem
      command: push
      tags: |
        latest